id = "everforest"
name = "Everforest Theme (regular, material, blur)"
schema_version = 1
version = "0.1.0"
authors = ["Albert Skonieczny <github.com/albertsko>"]
description = "A faithful port of sainnhe's Everforest theme for Zed. Comes in regular, material, and blur variants."
repository = "https://github.com/albertsko/zed-everforest"
