id = "everforest-port"
name = "Everforest"
schema_version = 1
version = "0.1.0"
authors = ["Albert Skonieczny <albertskonieczny@gmail.com>"]
description = "An exact port of Everforest vim color scheme for Zed. Comes in regular, material, and blur variants."
repository = "https://github.com/albertsko/zed-everforest"
